### ISSUE TITLE
Timebar / truncates the newest times when it should truncate the oldest.

### ISSUE THREAD

**Issue by gregchalmers** [wxtiles/wxtilesjs-example#18]
When there is allot of times the time bar shows the oldest times, not the newest.
I.e. it should truncate the oldest, currently it truncates the newest times

**Comment by alpha-beta-soup** [comment]
It's not a simple trunctation. Currently the application ignores every second timestamp recursively along the entire set of timestamps for a given layer until there are *n* timestamps. (It also always retains the first and last timestamps.) The objective is to preserve as much of the range of times as possible while removing small steps until there is a manageable number of steps for the simple application. The "direction" of this sub-samplling is right-to-left or left-to-right depending on whether the layer is forecast or observational: forecast layers prefer timestamps on the left (short-term forecasts are more important and accurate than long-term forecasts) and observational layers prefer timestamps on the right (recent observations more important than older observations).

https://github.com/wxtiles/mapbuilder/blob/gh-pages/createTileLayer.js#L12

I think this is the correct way to do this, so I won't fix this.

![screenshot from 2019-01-23 11-29-55](https://user-images.githubusercontent.com/5925045/51569793-41739400-1f02-11e9-8158-f2f65eb5ec53.png)
